import '../styles/globals.css';
import Nav from './components/Main/Nav';
import App from './page';
export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='pl'>
			<body className='font-inter bg-slate-700 text-slate-100'>
				<main className='relative flex flex-col max-w-4xl mx-auto h-screen'>
					{children}
				</main>
			</body>
		</html>
	);
}
